### ISSUE TITLE
  wording issue i think

### ISSUE THREAD

**Issue by tjhenderso** [Razviar/mtgap#397]
Cannot read properties of undefined (reading 'gradient'), TypeError: Cannot read properties of undefined (reading 'gradient')
    at https://dotgg.gg/wp-content/plugins/ProConnection-Dragonball/js/506.40c671d153f92be737be.js:1:5642
    at Array.map (<anonymous>)
    at w.render (https://dotgg.gg/wp-content/plugins/ProConnection-Dragonball/js/506.40c671d153f92be737be.js:1:5525)
    at Oa (https://dotgg.gg/wp-content/plugins/ProConnection-Dragonball/js/main.ddd36b0dfcfe52d5869d.js?ver=1.0.0:2:107631)
    at Ta (https://dotgg.gg/wp-content/plugins/ProConnection-Dragonball/js/main.ddd36b0dfcfe52d5869d.js?ver=1.0.0:2:107429)
    at kl (https://dotgg.gg/wp-content/plugins/ProConnection-Dragonball/js/main.ddd36b0dfcfe52d5869d.js?ver=1.0.0:2:150764)
    at wc (https://dotgg.gg/wp-content/plugins/ProConnection-Dragonball/js/main.ddd36b0dfcfe52d5869d.js?ver=1.0.0:2:138967)
    at bc (https://dotgg.gg/wp-content/plugins/ProConnection-Dragonball/js/main.ddd36b0dfcfe52d5869d.js?ver=1.0.0:2:138895)
    at vc (https://dotgg.gg/wp-content/plugins/ProConnection-Dragonball/js/main.ddd36b0dfcfe52d5869d.js?ver=1.0.0:2:138758)
    at oc (https://dotgg.gg/wp-content/plugins/ProConnection-Dragonball/js/main.ddd36b0dfcfe52d5869d.js?ver=1.0.0:2:135565), TypeError

**To Reproduce**

**Comment by Razviar** [comment]
Hello! On which page did you get this?

**Comment by Razviar** [comment]
Thanks for reporting, now it's resolved.
